<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>
    

    <xacro:property name="chassis_length"     value="0.210"/>
    <xacro:property name="chassis_width"      value="0.1005"/>
    <xacro:property name="chassis_height"     value="0.055"/>
    <xacro:property name="chassis_mass"       value="1.0"/>
    <xacro:property name="wheel_radius"       value="0.03"/>
    <xacro:property name="wheel_thickness"    value="0.03"/>
    <xacro:property name="wheel_offset_y"     value="0.06525"/>      <!--  (distance between left wheels and right wheels)/2 -->
    <xacro:property name="wheel_offset_x"     value="0.0785"/>      <!--  (distance between front wheels and back wheels)/2  -->
    <xacro:property name="wheel_mass"         value="0.06"/>

    <xacro:property name="collision_chassis_length"             value="0.21"/>
    <xacro:property name="collision_chassis_width"              value="0.1005"/>
    <xacro:property name="collision_chassis_height"             value="0.085"/>
    <xacro:property name="collision_chassis_height_offset"      value="${collision_chassis_height/2}"/>
    

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="green">
        <color rgba="0 1 0 1"/>
    </material>
    

    <!-- BASE_FOOTPRINT LINK  (shadow of the base_link in 2D plane)-->

    <link name="base_footprint"/>

    <!-- BASE LINK -->

    <link name="base_link"/>

    <!-- BASE JOINT -->

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -0.030" rpy="0 0 0"/>
    </joint>

    <!-- CHASSIS LINK -->

    <link name="chassis_link">
        <visual>
            <origin xyz="0 0 -0.015" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://slambot/meshes/slambot_body.stl" scale="1.0 1.0 1.0"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${collision_chassis_height_offset}"/>
            <geometry>
                <box size="${collision_chassis_length} ${collision_chassis_width} ${collision_chassis_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- CHASSIS JOINT -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>


    <!-- WHEEL LEFT LINK -->

    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://slambot/meshes/wheel.stl" scale="1.0 1.0 1.0"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${wheel_mass}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>


    <!-- LEFT WHEEL JOINT -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="-${wheel_offset_x} ${wheel_offset_y} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <!-- RIGHT WHEEL LINK -->

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
            <geometry>
                <mesh filename="package://slambot/meshes/wheel.stl" scale="1.0 1.0 1.0"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${wheel_mass}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <!-- RIGHT WHEEL JOINT -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="-${wheel_offset_x} -${wheel_offset_y} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>


    <!-- ________________ Fixed Wheels __________________-->

    <!-- FL WHEEL LINK -->

    <link name="fl_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://slambot/meshes/wheel.stl" scale="1.0 1.0 1.0"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${wheel_mass}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>


    <!-- FL WHEEL JOINT -->

    <joint name="fl_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="fl_wheel"/>
        <origin xyz="${wheel_offset_x} ${wheel_offset_y} 0" rpy="0 0 0"/>
    </joint>

    <!-- FR WHEEL LINK -->

    <link name="fr_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
            <geometry>
                <mesh filename="package://slambot/meshes/wheel.stl" scale="1.0 1.0 1.0"/>
                <!-- <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/> -->
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${wheel_mass}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>


    <!-- FR WHEEL JOINT -->

    <joint name="fr_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="fr_wheel"/>
        <origin xyz="${wheel_offset_x} -${wheel_offset_y} 0" rpy="0 0 0"/>
    </joint>

</robot>